# TODO: Paginate instead of 999 limit
query allGamesQuery {
  gameCollection(limit: 999, order: [title_ASC]) {
    items {
      title
      slug
      system {
        slug
        shortName
      }
      playedStatus
      wtbWts
    }
  }
}
