# TODO: Paginate instead of 999 limit
query allImagesQuery {
  assetCollection(limit: 999, order: sys_firstPublishedAt_DESC) {
    items {
      url
      thumbnail: url(
        transform: { width: 300, height: 200, resizeStrategy: FILL }
      )
    }
  }
}
