query allSystemsQuery {
  systemCollection(order: [title_ASC]) {
    items {
      title
      shortName
      slug
      cover {
        thumbnail: url(transform: { width: 400, format: WEBP })
        title
      }
      linkedFrom {
        gameCollection {
          total
        }
      }
    }
  }
}
