query currentlyPlayingGamesQuery {
  gameCollection(where: { currentlyPlaying: true }, order: [title_ASC]) {
    items {
      sys {
        id
      }
      title
      slug
      system {
        slug
        shortName
      }
      playedStatus
      digital
      region
      cover {
        thumbnail: url(transform: { width: 400 })
        load: url(transform: { width: 100, quality: 5 })
        title
      }
    }
  }
}
