query gameBySlugQuery($slug: String!) {
  gameCollection(where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
      }
      title
      system {
        title
        shortName
        slug
        manufacturer {
          title
        }
      }
      region
      playedStatus
      requirementsForCompletion
      wtbWts
      photosCollection(limit: 10) {
        items {
          url
          thumbnail: url(
            transform: { width: 300, height: 200, resizeStrategy: FILL }
          )
        }
      }
    }
  }

  gameLogCollection(where: { game: { slug: $slug } }) {
    items {
      sys {
        firstPublishedAt
      }
      title
      slug
    }
  }
}
