query gamesBySystemQuery($system: String!) {
  gameCollection(limit: 999, where: { system: { slug: $system } }, order: [title_ASC]) {
    items {
      sys {
        id
      }
      title
      slug
      playedStatus
      digital
      wtbWts
      system {
        slug
      }
      region
    }
  }
}
