query gamesBySystemQuery($system: String!) {
  gameCollection(
    limit: 999
    where: { system: { slug: $system } }
    order: [title_ASC]
  ) {
    items {
      sys {
        id
      }
      title
      slug
      playedStatus
      digital
      system {
        slug
      }
      region
      cover {
        thumbnail: url(transform: { width: 400 })
        load: url(transform: { width: 100, quality: 5 })
        title
      }
    }
  }
}
