query gameLogBySlugQuery($slug: String!) {
  gameLogCollection(where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
        firstPublishedAt
      }
      title
      game {
        title
        slug
        system {
          slug
        }
      }
      details {
        json
      }
    }
  }
}
