query gameLogBySlugQuery($slug: String!) {
  gameLogCollection(where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
        firstPublishedAt
      }
      title
      game {
        title
        slug
        system {
          slug
        }
        region
        cover {
          thumbnail: url(transform: { width: 400, format: WEBP })
          title
        }
      }
      details {
        json
        links {
          assets {
            block {
              sys {
                id
              }
              url(transform: { width: 500, format: WEBP })
              title
              description
              contentType
            }
          }
        }
      }
    }
  }
}
