query gameBySlugAndSystemQuery($slug: String!, $system: String!) {
  gameCollection(where: { slug: $slug, system: { slug: $system } }, limit: 1) {
    items {
      sys {
        id
        firstPublishedAt
        publishedAt
      }
      title
      system {
        title
        shortName
        slug
        manufacturer {
          title
        }
      }
      region
      playedStatus
      highScore
      digital
      requirementsForCompletion
      cover {
        full: url(transform: { width: 1440, format: WEBP })
      }
      photosCollection(limit: 10) {
        items {
          url
          thumbnail: url(
            transform: { width: 300, height: 200, resizeStrategy: FILL }
          )
        }
      }
    }
  }

  gameLogCollection(where: { game: { slug: $slug } }) {
    items {
      sys {
        firstPublishedAt
      }
      title
      slug
    }
  }
}
