query gamesBySystemQuery($system: String!) {
  gameCollection(where: { system: { slug: $system } }, order: [title_ASC]) {
    items {
      sys {
        id
      }
      title
      slug
      playedStatus
      wtbWts
      system {
        slug
      }
    }
  }
}
