query latestGamesQuery {
  gameCollection(limit: 12, order: [sys_firstPublishedAt_DESC]) {
    items {
      sys {
        firstPublishedAt
      }
      title
      system {
        slug
        shortName
      }
      digital
      slug
      region
      playedStatus
      cover {
        thumbnail: url(transform: { width: 400, format: WEBP })
        title
      }
    }
  }
}
