query recentlyUpdatedQuery {
  gameCollection(
    limit: 12
    order: [sys_publishedAt_DESC]
    where: { sys: { publishedVersion_gt: 4 } }
  ) {
    items {
      sys {
        publishedAt
      }
      title
      system {
        slug
        shortName
      }
      digital
      slug
      region
      cover {
        thumbnail: url(transform: { width: 400 })
        load: url(transform: { width: 100, quality: 5 })
        title
      }
    }
  }
}
