query recentlyUpdatedQuery {
  gameCollection(limit: 3, where: {sys:{publishedVersion_gt:4}}) {
    items {
      sys {
        publishedAt
      }
      title
      system {
        slug
        shortName
      }
      digital
      slug
      region
    }
  }
}
