query recentlyUpdatedQuery {
  gameCollection(
    limit: 12
    order: [sys_publishedAt_DESC]
    where: { sys: { publishedVersion_gt: 4 } }
  ) {
    items {
      sys {
        publishedAt
      }
      title
      system {
        slug
        shortName
      }
      slug
      region
      playedStatus
      cover {
        thumbnail: url(transform: { width: 400, format: WEBP, quality: 5 })
        title
      }
    }
  }
}
