query statistics {
  games: gameCollection {
    total
  }
  gamesBeaten: gameCollection(where: { playedStatus: "Beaten" }) {
    total
  }
  gamesCompleted: gameCollection(where: { playedStatus: "Completed" }) {
    total
  }
  gamesUnfinished: gameCollection(where: { playedStatus: "Unfinished" }) {
    total
  }
  gamesUntouched: gameCollection(where: { playedStatus: "Untouched" }) {
    total
  }
  gamesAbandoned: gameCollection(where: { playedStatus: "Abandoned" }) {
    total
  }
  systems: systemCollection(order: [title_ASC]) {
    total
    items {
      title
      shortName
      linkedFrom {
        gameCollection {
          total
        }
      }
    }
  }
}
