query systemBySlug($slug: String!) {
  systemCollection(where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
      }
      title
      shortName
      manufacturer {
        title
        logo {
          image: url(transform: { height: 20, format: PNG })
        }
      }
    }
  }
}
