query systemBySlugQuery($slug: String!) {
  systemCollection(where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
      }
      title
      shortName
      manufacturer {
        title
      }
    }
  }
}
